#!/usr/bin/env node
/**
 * wire — sinh entry point ALICE cho project từ base prompt đã bake.
 *
 * Chỉ dùng Node built-in. Script chạy trong knowledge/ và ghi vào project cha.
 *
 * Ba lớp entry point, cố ý khác nhau về cơ chế:
 *   1. ALICE.md ở root  — file Bệ hạ đính kèm thủ công cho agent nào cũng dùng được.
 *   2. CLAUDE.md / AGENTS.md / GEMINI.md — client TỰ nạp mỗi phiên, không cần gõ gì.
 *      Đây là lớp duy nhất còn hiệu lực khi người dùng quên gọi /alice.
 *   3. Skill/command `/alice` — nạp trọn base prompt khi được gọi tường minh.
 *
 * File đã có mà không mang marker ALICE sẽ KHÔNG bị ghi đè. Với ba file auto-load ở
 * lớp 2, chỉ khối giữa hai marker bị thay; nội dung của người dùng giữ nguyên.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const PROJECT_ROOT = path.resolve(ROOT, "..");
const KNOWLEDGE_DIR = path.basename(ROOT);
const PROMPT_FILE = path.join(ROOT, "prompts.md");
const MARKER = "Generated by ALICE CODING. Source: knowledge/prompts.md.";
const BLOCK_BEGIN = "<!-- BEGIN ALICE CODING -->";
const BLOCK_END = "<!-- END ALICE CODING -->";
const REMINDER_COMMAND = `node ${KNOWLEDGE_DIR}/tools/reminder.js`;

function fail(message, code = 1) {
  console.error(`ALICE wire failed: ${message}`);
  process.exit(code);
}

function readBakedPrompt() {
  if (!fs.existsSync(PROMPT_FILE)) {
    fail("prompts.md was not found. Complete INITIALIZATION Step 7 first.");
  }
  const prompt = fs.readFileSync(PROMPT_FILE, "utf8").trim();
  if (!prompt) fail("prompts.md is empty.");
  if (!prompt.includes("## NHIỆM VỤ")) {
    fail("prompts.md is not an ALICE vibe base prompt (missing '## NHIỆM VỤ').");
  }
  const placeholders = ["<PROJECT>", "<Bệ hạ chỉ cần điền việc cần làm ở đây>"];
  const unresolved = placeholders.find((value) => prompt.includes(value));
  if (unresolved) {
    fail(`prompts.md still contains the unresolved placeholder ${unresolved}.`);
  }
  return prompt;
}

/**
 * Cắt phần "## NHIỆM VỤ" khỏi base prompt.
 *
 * Mỗi target tự gắn khối nhiệm vụ theo cú pháp của chính client ($ARGUMENTS, {{args}}...).
 * Giữ lại khối cũ của prompts.md sẽ để hai mục NHIỆM VỤ chồng nhau trong cùng một file,
 * và agent không biết mục nào là việc thật của lượt này.
 */
function stripTaskSection(prompt) {
  const lines = prompt.split(/\r?\n/);
  const start = lines.reduce(
    (found, line, index) => (/^#{1,6}\s*NHIỆM VỤ\s*$/.test(line.trim()) ? index : found),
    -1,
  );
  if (start === -1) return prompt.trim();
  return lines.slice(0, start).join("\n").trim();
}

function markdownAdapter(frontmatter, prompt, taskBlock) {
  return [
    "---",
    ...frontmatter,
    "---",
    "",
    `<!-- ${MARKER} -->`,
    "",
    "Nạp toàn bộ chỉ dẫn dưới đây làm chỉ dẫn đứng cho phiên làm việc hiện tại.",
    "Nếu có xung đột, system/developer instruction và luật project có ưu tiên cao hơn.",
    "",
    prompt,
    "",
    "## NHIỆM VỤ CỦA LƯỢT NÀY",
    taskBlock,
    "",
  ].join("\n");
}

/** ALICE.md ở root project — bản đính kèm thủ công, dùng được với mọi agent. */
function rootEntryPoint(prompt) {
  return [
    "# ALICE.md — entry point của project",
    "",
    `<!-- ${MARKER} Do not edit by hand; run \`npm run wire\` inside ${KNOWLEDGE_DIR}/. -->`,
    "",
    "File này là **base prompt đã bake** của project. Ba cách dùng, cùng một nội dung:",
    "",
    "| Agent | Cách gọi |",
    "| --- | --- |",
    "| Claude Code, OpenCode, Gemini CLI | `/alice <task>` |",
    "| Codex | `$alice <task>` hoặc chọn `alice` trong `/skills` |",
    "| Agent khác / chat web | đính kèm chính file này rồi viết nhiệm vụ |",
    "",
    `Hiến pháp đầy đủ nằm ở \`${KNOWLEDGE_DIR}/ALICE.md\`; đặc tả riêng của project ở`,
    `\`${KNOWLEDGE_DIR}/ALICE.project.md\`. File này chỉ là cửa vào, không thay thế hai file đó.`,
    "",
    "---",
    "",
    prompt,
    "",
    "## NHIỆM VỤ",
    "",
    "<!-- Đính kèm file này rồi viết nhiệm vụ trong chat, hoặc điền vào ngay dưới dòng này. -->",
    "",
  ].join("\n");
}

/**
 * Khối luật ngắn nhét vào file mà client TỰ nạp mỗi phiên.
 *
 * Cố ý KHÔNG chép cả base prompt vào đây: ba file này đi kèm mọi request, chép trọn
 * prompt là trả token cho phần lớn lượt không cần tới. Khối này chỉ giữ đúng những luật
 * mà bỏ sót là hỏng task, cộng con trỏ tới ALICE.md.
 */
function autoContextBlock() {
  return [
    BLOCK_BEGIN,
    `<!-- ${MARKER} Do not edit inside this block; run \`npm run wire\` inside ${KNOWLEDGE_DIR}/. -->`,
    "",
    "## ALICE — luật bắt buộc của project này",
    "",
    "Bạn là **Alice**. Đọc `./ALICE.md` (base prompt đã bake) **trước khi gõ dòng code đầu tiên**",
    `của mỗi phiên; luật đầy đủ ở \`${KNOWLEDGE_DIR}/ALICE.md\` + \`${KNOWLEDGE_DIR}/ALICE.project.md\`.`,
    "Năm luật dưới đây có hiệu lực **cho mọi lượt**, kể cả khi người dùng không gọi `/alice`:",
    "",
    "1. **Nạp ký ức trước mọi task.** Brain bật → gọi MCP `search`/`grep`/`get_entity` theo",
    `   \`${KNOWLEDGE_DIR}/brain/RETRIEVAL.md\`, rồi in checklist "ký ức đã nạp" kèm số tool call`,
    `   và citation. Brain offline → đọc \`${KNOWLEDGE_DIR}/mistakes/LOG.md\` (theo tag) + **toàn bộ**`,
    `   entry \`ACTIVE\` trong \`${KNOWLEDGE_DIR}/decisions/LOG.md\` + \`${KNOWLEDGE_DIR}/wiki/ROUTER.md\``,
    `   + digest gần nhất trong \`${KNOWLEDGE_DIR}/context/\`, và **báo cho người dùng biết brain offline**.`,
    "2. **Sau auto-compact hoặc khi thấy mơ hồ về điều đã quyết** → đọc lại `./ALICE.md`, đọc lại",
    "   `decisions`/`mistakes` và **re-query brain** trước khi làm tiếp. Không chắc có bị compact?",
    "   Cứ coi như có. Không suy đoán tiếp từ ký ức mờ.",
    "3. **Sub-agent đi qua Brain, không dò CLI trên host.** `list_sub_agents` → chọn slot",
    "   `callable=yes` → `ask_sub_agent`. Credential được giải mã trong Brain; không cần và không",
    "   được đòi biến môi trường trên máy. Chỉ mode `host-cli` mới mở CLI, và phải",
    "   `log_agent_task(started)` trước, `done|failed` sau.",
    `4. **Ghi tri thức theo TURN, rồi phải sync.** File Markdown trong \`${KNOWLEDGE_DIR}/\` là`,
    "   source-of-truth — ghi thẳng vào file là **đúng**; Brain **không có** tool ghi tri thức.",
    "   Nhưng ghi xong mà chưa `npm run verify` → `npm run sync` thì brain chưa biết gì, và lượt",
    "   sau sẽ recall trượt. Chưa sync = **task chưa xong**.",
    "5. **Không xong giả.** Chỉ tuyên bố PASS cho phần có bằng chứng đã chạy; phần chưa test được",
    "   phải nói thẳng và biến thành next step.",
    "",
    `Lệnh chạy trong \`${KNOWLEDGE_DIR}/\`: \`npm run brain\` · \`npm run verify\` · \`npm run sync\` ·`,
    "`npm run update` · `npm run wire`.",
    "",
    BLOCK_END,
  ].join("\n");
}

function buildOwnedTargets(prompt) {
  const description = "Nạp base prompt ALICE đã bake và bắt đầu một task vibe coding theo đúng rules, memory, telemetry và verify của project.";
  const portable = markdownAdapter(
    [
      "name: alice",
      `description: ${description}`,
    ],
    prompt,
    "Nội dung người dùng viết cùng lời gọi skill `$alice` là nhiệm vụ cần thực hiện. Nếu chưa có nhiệm vụ, hỏi đúng một câu ngắn để lấy nhiệm vụ.",
  );
  const claude = markdownAdapter(
    [
      "name: alice",
      `description: ${description}`,
      "disable-model-invocation: true",
      "argument-hint: <task>",
    ],
    prompt,
    "$ARGUMENTS",
  );
  const opencode = markdownAdapter(
    [
      `description: ${description}`,
    ],
    prompt,
    "$ARGUMENTS",
  );
  const geminiPrompt = [
    `<!-- ${MARKER} -->`,
    "Nạp toàn bộ chỉ dẫn dưới đây làm chỉ dẫn đứng cho phiên làm việc hiện tại.",
    "Nếu có xung đột, system/developer instruction và luật project có ưu tiên cao hơn.",
    "",
    prompt,
    "",
    "## NHIỆM VỤ CỦA LƯỢT NÀY",
    "{{args}}",
  ].join("\n");
  const gemini = [
    `# ${MARKER}`,
    `description = ${JSON.stringify(description)}`,
    `prompt = ${JSON.stringify(geminiPrompt)}`,
    "",
  ].join("\n");

  return [
    [path.join(PROJECT_ROOT, "ALICE.md"), rootEntryPoint(prompt), "Project entry point"],
    [path.join(PROJECT_ROOT, ".agents", "skills", "alice", "SKILL.md"), portable, "Codex/OpenCode skill"],
    [path.join(PROJECT_ROOT, ".claude", "skills", "alice", "SKILL.md"), claude, "Claude Code skill"],
    [path.join(PROJECT_ROOT, ".opencode", "commands", "alice.md"), opencode, "OpenCode command"],
    [path.join(PROJECT_ROOT, ".gemini", "commands", "alice.toml"), gemini, "Gemini CLI command"],
  ];
}

/** File auto-load của từng client. Nội dung người dùng KHÔNG bị đụng. */
const AUTO_CONTEXT_FILES = [
  ["CLAUDE.md", "Claude Code auto-context"],
  ["AGENTS.md", "Codex/OpenCode auto-context"],
  ["GEMINI.md", "Gemini CLI auto-context"],
];

function isAliceOwned(file) {
  return fs.existsSync(file) && fs.readFileSync(file, "utf8").includes(MARKER);
}

function writeOwned(targets) {
  const conflicts = targets
    .filter(([file]) => fs.existsSync(file) && !isAliceOwned(file))
    .map(([file]) => path.relative(PROJECT_ROOT, file));
  if (conflicts.length) {
    fail(`refusing to overwrite non-ALICE file(s): ${conflicts.join(", ")}`, 2);
  }

  for (const [file, content, label] of targets) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, "utf8");
    console.log(`  ${"WIRED".padEnd(7)} ${label}: ${path.relative(PROJECT_ROOT, file)}`);
  }
}

function mergeBlock(existing, block) {
  const begin = existing.indexOf(BLOCK_BEGIN);
  const end = existing.indexOf(BLOCK_END);
  if (begin !== -1 && end !== -1 && end > begin) {
    return existing.slice(0, begin) + block + existing.slice(end + BLOCK_END.length);
  }
  const head = existing.trim();
  return head ? `${head}\n\n${block}\n` : `${block}\n`;
}

function writeAutoContext() {
  for (const [name, label] of AUTO_CONTEXT_FILES) {
    const file = path.join(PROJECT_ROOT, name);
    const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    const next = mergeBlock(existing, autoContextBlock());
    if (next === existing) {
      console.log(`  ${"OK".padEnd(7)} ${label}: ${name} (already current)`);
      continue;
    }
    fs.writeFileSync(file, next, "utf8");
    console.log(`  ${(existing ? "UPDATED" : "WIRED").padEnd(7)} ${label}: ${name}`);
  }
}

/**
 * Hook SessionStart của Claude Code: sau mỗi lần compact, in lại ALICE.md vào context.
 *
 * Đây là lớp duy nhất chạy NGOÀI model, nên là thứ duy nhất không bị auto-compact xoá.
 * Chỉ thêm hook mang đúng command của ALICE; mọi key khác trong settings.json giữ nguyên.
 */
function writeClaudeHook() {
  const file = path.join(PROJECT_ROOT, ".claude", "settings.json");
  let settings = {};
  if (fs.existsSync(file)) {
    const raw = fs.readFileSync(file, "utf8").trim();
    if (raw) {
      try {
        settings = JSON.parse(raw);
      } catch (error) {
        console.warn(
          `  SKIP   Claude Code compact hook: .claude/settings.json is not valid JSON (${error.message}).`,
        );
        console.warn("         Fix the file and run `npm run wire` again to install the hook.");
        return false;
      }
    }
  }
  if (!settings || typeof settings !== "object" || Array.isArray(settings)) {
    console.warn("  SKIP   Claude Code compact hook: .claude/settings.json is not a JSON object.");
    return false;
  }

  const hooks = settings.hooks && typeof settings.hooks === "object" ? settings.hooks : {};
  const sessionStart = Array.isArray(hooks.SessionStart) ? hooks.SessionStart : [];
  const owned = (entry) =>
    Array.isArray(entry && entry.hooks) &&
    entry.hooks.some((hook) => typeof hook.command === "string" && hook.command.includes("tools/reminder.js"));
  // KHÔNG đặt `matcher`. `SessionStart` phân biệt phiên bằng `source`
  // (`startup|resume|clear|compact|fork`) và tài liệu của Claude Code ghi matcher của event
  // này là "-". Bỏ trống thì hook chạy cho mọi source, kể cả `compact` — đúng thứ cần. Viết
  // một chuỗi alternation vào đây là đặt cược rằng matcher được so bằng regex chứ không phải
  // so bằng chuỗi; đoán sai thì hook im lặng không bao giờ chạy.
  const entry = {
    hooks: [{ type: "command", command: REMINDER_COMMAND }],
  };
  const next = sessionStart.filter((item) => !owned(item)).concat([entry]);

  settings.hooks = Object.assign({}, hooks, { SessionStart: next });
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
  console.log(`  ${"WIRED".padEnd(7)} Claude Code compact hook: .claude/settings.json`);
  return true;
}

const baked = stripTaskSection(readBakedPrompt());
writeOwned(buildOwnedTargets(baked));
writeAutoContext();
const hooked = writeClaudeHook();

console.log("\nALICE entry points are ready:");
console.log("  Claude Code / OpenCode / Gemini CLI: /alice <task>");
console.log("  Codex: $alice <task> (Codex does not expose repo skills as /alice)");
console.log("  Any other agent: attach ALICE.md and write the task");
console.log("  CLAUDE.md / AGENTS.md / GEMINI.md carry the rules even when nobody calls /alice");
if (hooked) {
  console.log("  Claude Code reloads ALICE.md automatically after every auto-compact");
}
console.log("Commit the generated files with the project so the team gets the same entry point.");
