"use strict";

const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");
const test = require("node:test");

const SOURCE = path.join(__dirname, "wire.js");
const REMINDER_SOURCE = path.join(__dirname, "reminder.js");

const BAKED = "# Base\n\nProject demo.\n\n## NHIỆM VỤ\n<đã bake>";

function fixture(prompt = BAKED) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "alice-wire-"));
  const knowledge = path.join(root, "project", "knowledge");
  const tools = path.join(knowledge, "tools");
  fs.mkdirSync(tools, { recursive: true });
  fs.copyFileSync(SOURCE, path.join(tools, "wire.js"));
  fs.copyFileSync(REMINDER_SOURCE, path.join(tools, "reminder.js"));
  fs.writeFileSync(path.join(knowledge, "prompts.md"), prompt, "utf8");
  const project = path.join(root, "project");
  return {
    root,
    project,
    knowledge,
    read: (rel) => fs.readFileSync(path.join(project, rel), "utf8"),
    run: () => spawnSync(process.execPath, [path.join(tools, "wire.js")], { encoding: "utf8" }),
    reminder: () =>
      spawnSync(process.execPath, [path.join(tools, "reminder.js")], {
        cwd: project,
        encoding: "utf8",
      }),
    cleanup: () => fs.rmSync(root, { recursive: true, force: true }),
  };
}

const ADAPTERS = [
  ".agents/skills/alice/SKILL.md",
  ".claude/skills/alice/SKILL.md",
  ".opencode/commands/alice.md",
  ".gemini/commands/alice.toml",
];

test("wire creates and refreshes every supported project adapter", () => {
  const fx = fixture();
  try {
    const first = fx.run();
    assert.strictEqual(first.status, 0, first.stderr);

    for (const rel of ADAPTERS) {
      const content = fx.read(rel);
      assert.match(content, /Generated by ALICE CODING/);
      assert.match(content, /Project demo/);
    }
    const gemini = fx.read(ADAPTERS[3]);
    const promptLine = gemini.split(/\r?\n/).find((line) => line.startsWith("prompt = "));
    assert.ok(promptLine);
    assert.match(JSON.parse(promptLine.slice("prompt = ".length)), /\{\{args\}\}/);

    fs.writeFileSync(
      path.join(fx.knowledge, "prompts.md"),
      "# Base\n\nProject demo v2.\n\n## NHIỆM VỤ\n<đã bake>",
      "utf8",
    );
    const second = fx.run();
    assert.strictEqual(second.status, 0, second.stderr);
    assert.match(fx.read(ADAPTERS[0]), /Project demo v2/);
  } finally {
    fx.cleanup();
  }
});

test("wire drops the stale task section so only one task block survives", () => {
  const fx = fixture("# Base\n\nProject demo.\n\n## NHIỆM VỤ\nviệc cũ còn sót lại");
  try {
    assert.strictEqual(fx.run().status, 0);
    for (const rel of ADAPTERS) {
      assert.doesNotMatch(fx.read(rel), /việc cũ còn sót lại/);
    }
    assert.doesNotMatch(fx.read("ALICE.md"), /việc cũ còn sót lại/);
  } finally {
    fx.cleanup();
  }
});

test("wire writes a root entry point that carries the baked prompt", () => {
  const fx = fixture();
  try {
    assert.strictEqual(fx.run().status, 0);
    const entry = fx.read("ALICE.md");
    assert.match(entry, /Generated by ALICE CODING/);
    assert.match(entry, /Project demo/);
    assert.match(entry, /knowledge\/ALICE\.md/);
    assert.match(entry, /## NHIỆM VỤ/);
  } finally {
    fx.cleanup();
  }
});

test("wire injects the rules block into auto-context files without eating user content", () => {
  const fx = fixture();
  try {
    fs.writeFileSync(path.join(fx.project, "AGENTS.md"), "# Luật riêng của team\n\nGiữ nguyên dòng này.\n", "utf8");
    assert.strictEqual(fx.run().status, 0);

    for (const name of ["CLAUDE.md", "AGENTS.md", "GEMINI.md"]) {
      const content = fx.read(name);
      assert.match(content, /<!-- BEGIN ALICE CODING -->/);
      assert.match(content, /<!-- END ALICE CODING -->/);
      assert.match(content, /Nạp ký ức trước mọi task/);
      // Khối auto-load cố ý KHÔNG chép cả base prompt: nó đi kèm mọi request.
      assert.doesNotMatch(content, /Project demo/);
    }
    assert.match(fx.read("AGENTS.md"), /Giữ nguyên dòng này/);

    // Chạy lại: khối được thay tại chỗ, không nhân bản, nội dung người dùng còn nguyên.
    assert.strictEqual(fx.run().status, 0);
    const agents = fx.read("AGENTS.md");
    assert.strictEqual(agents.match(/<!-- BEGIN ALICE CODING -->/g).length, 1);
    assert.match(agents, /Giữ nguyên dòng này/);
  } finally {
    fx.cleanup();
  }
});

test("wire installs the compact hook and keeps foreign settings intact", () => {
  const fx = fixture();
  try {
    const settingsFile = path.join(fx.project, ".claude", "settings.json");
    fs.mkdirSync(path.dirname(settingsFile), { recursive: true });
    fs.writeFileSync(
      settingsFile,
      JSON.stringify({
        permissions: { allow: ["Bash(npm run verify)"] },
        hooks: { SessionStart: [{ matcher: "startup", hooks: [{ type: "command", command: "echo mine" }] }] },
      }),
      "utf8",
    );

    assert.strictEqual(fx.run().status, 0);
    let settings = JSON.parse(fs.readFileSync(settingsFile, "utf8"));
    assert.deepStrictEqual(settings.permissions.allow, ["Bash(npm run verify)"]);
    assert.strictEqual(settings.hooks.SessionStart.length, 2);
    assert.strictEqual(settings.hooks.SessionStart[0].hooks[0].command, "echo mine");
    const alice = settings.hooks.SessionStart[1];
    // Không có matcher = chạy cho mọi source của SessionStart, kể cả `compact`.
    assert.strictEqual("matcher" in alice, false);
    assert.match(alice.hooks[0].command, /tools\/reminder\.js$/);

    // Chạy lại không được nhân đôi hook của ALICE.
    assert.strictEqual(fx.run().status, 0);
    settings = JSON.parse(fs.readFileSync(settingsFile, "utf8"));
    assert.strictEqual(settings.hooks.SessionStart.length, 2);
  } finally {
    fx.cleanup();
  }
});

test("wire keeps a broken settings.json instead of clobbering it", () => {
  const fx = fixture();
  try {
    const settingsFile = path.join(fx.project, ".claude", "settings.json");
    fs.mkdirSync(path.dirname(settingsFile), { recursive: true });
    fs.writeFileSync(settingsFile, "{ not json", "utf8");

    const result = fx.run();
    assert.strictEqual(result.status, 0, result.stderr);
    assert.match(result.stderr, /SKIP\s+Claude Code compact hook/);
    assert.strictEqual(fs.readFileSync(settingsFile, "utf8"), "{ not json");
    // Phần còn lại vẫn phải được sinh, không vì hook hỏng mà bỏ dở.
    assert.match(fx.read("ALICE.md"), /Project demo/);
  } finally {
    fx.cleanup();
  }
});

test("reminder replays the generated entry point for the compact hook", () => {
  const fx = fixture();
  try {
    assert.strictEqual(fx.run().status, 0);
    const result = fx.reminder();
    assert.strictEqual(result.status, 0, result.stderr);
    assert.match(result.stdout, /<alice-entry-point>/);
    assert.match(result.stdout, /Project demo/);
    assert.match(result.stdout, /auto-compact/);
  } finally {
    fx.cleanup();
  }
});

test("reminder stays quiet on stdout when the entry point is missing", () => {
  const fx = fixture();
  try {
    const result = fx.reminder();
    assert.strictEqual(result.status, 0);
    assert.strictEqual(result.stdout, "");
    assert.match(result.stderr, /ALICE\.md was not found/);
  } finally {
    fx.cleanup();
  }
});

test("wire refuses all writes when an alice adapter belongs to the user", () => {
  const fx = fixture();
  try {
    const conflict = path.join(fx.project, ".claude", "skills", "alice", "SKILL.md");
    fs.mkdirSync(path.dirname(conflict), { recursive: true });
    fs.writeFileSync(conflict, "user-owned command", "utf8");

    const result = fx.run();
    assert.strictEqual(result.status, 2);
    assert.match(result.stderr, /refusing to overwrite non-ALICE file/);
    assert.strictEqual(
      fs.existsSync(path.join(fx.project, ".agents", "skills", "alice", "SKILL.md")),
      false,
    );
    assert.strictEqual(fs.existsSync(path.join(fx.project, "ALICE.md")), false);
    assert.strictEqual(fs.readFileSync(conflict, "utf8"), "user-owned command");
  } finally {
    fx.cleanup();
  }
});

test("wire refuses to overwrite a project ALICE.md it did not write", () => {
  const fx = fixture();
  try {
    fs.writeFileSync(path.join(fx.project, "ALICE.md"), "# Tài liệu của Bệ hạ\n", "utf8");
    const result = fx.run();
    assert.strictEqual(result.status, 2);
    assert.match(result.stderr, /ALICE\.md/);
    assert.strictEqual(fx.read("ALICE.md"), "# Tài liệu của Bệ hạ\n");
  } finally {
    fx.cleanup();
  }
});

test("wire rejects an unbaked prompt", () => {
  const fx = fixture("# Base <PROJECT>\n\n## NHIỆM VỤ\n<Bệ hạ chỉ cần điền việc cần làm ở đây>");
  try {
    const result = fx.run();
    assert.strictEqual(result.status, 1);
    assert.match(result.stderr, /unresolved placeholder/);
  } finally {
    fx.cleanup();
  }
});
