"use strict";

const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");
const test = require("node:test");

const SOURCE = path.join(__dirname, "wire.js");

function fixture(prompt = "# Base\n\nProject demo.\n\n## NHIỆM VỤ\nĐược điền khi gọi.") {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "alice-wire-"));
  const knowledge = path.join(root, "project", "knowledge");
  const tools = path.join(knowledge, "tools");
  fs.mkdirSync(tools, { recursive: true });
  fs.copyFileSync(SOURCE, path.join(tools, "wire.js"));
  fs.writeFileSync(path.join(knowledge, "prompts.md"), prompt, "utf8");
  return {
    root,
    project: path.join(root, "project"),
    knowledge,
    run: () => spawnSync(process.execPath, [path.join(tools, "wire.js")], { encoding: "utf8" }),
    cleanup: () => fs.rmSync(root, { recursive: true, force: true }),
  };
}

test("wire creates and refreshes every supported project adapter", () => {
  const fx = fixture();
  try {
    const first = fx.run();
    assert.strictEqual(first.status, 0, first.stderr);

    const files = [
      ".agents/skills/alice/SKILL.md",
      ".claude/skills/alice/SKILL.md",
      ".opencode/commands/alice.md",
      ".gemini/commands/alice.toml",
    ];
    for (const rel of files) {
      const content = fs.readFileSync(path.join(fx.project, rel), "utf8");
      assert.match(content, /Generated by ALICE CODING/);
      assert.match(content, /Project demo/);
    }
    const gemini = fs.readFileSync(path.join(fx.project, files[3]), "utf8");
    const promptLine = gemini.split(/\r?\n/).find((line) => line.startsWith("prompt = "));
    assert.ok(promptLine);
    assert.match(JSON.parse(promptLine.slice("prompt = ".length)), /\{\{args\}\}/);

    fs.writeFileSync(
      path.join(fx.knowledge, "prompts.md"),
      "# Base\n\nProject demo v2.\n\n## NHIỆM VỤ\nĐược điền khi gọi.",
      "utf8",
    );
    const second = fx.run();
    assert.strictEqual(second.status, 0, second.stderr);
    assert.match(
      fs.readFileSync(path.join(fx.project, files[0]), "utf8"),
      /Project demo v2/,
    );
  } finally {
    fx.cleanup();
  }
});

test("wire refuses all writes when an alice adapter belongs to the user", () => {
  const fx = fixture();
  try {
    const conflict = path.join(fx.project, ".claude", "skills", "alice", "SKILL.md");
    fs.mkdirSync(path.dirname(conflict), { recursive: true });
    fs.writeFileSync(conflict, "user-owned command", "utf8");

    const result = fx.run();
    assert.strictEqual(result.status, 2);
    assert.match(result.stderr, /refusing to overwrite non-ALICE adapter/);
    assert.strictEqual(
      fs.existsSync(path.join(fx.project, ".agents", "skills", "alice", "SKILL.md")),
      false,
    );
    assert.strictEqual(fs.readFileSync(conflict, "utf8"), "user-owned command");
  } finally {
    fx.cleanup();
  }
});

test("wire rejects an unbaked prompt", () => {
  const fx = fixture("# Base <PROJECT>\n\n## NHIỆM VỤ\n<Bệ hạ chỉ cần điền việc cần làm ở đây>");
  try {
    const result = fx.run();
    assert.strictEqual(result.status, 1);
    assert.match(result.stderr, /unresolved placeholder/);
  } finally {
    fx.cleanup();
  }
});
