#!/usr/bin/env node
/**
 * wire — sinh adapter /alice từ base prompt đã bake của project.
 *
 * Chỉ dùng Node built-in. Script chạy trong knowledge/ và ghi adapter vào project
 * cha. File đã có mà không mang marker ALICE sẽ KHÔNG bị ghi đè.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const PROJECT_ROOT = path.resolve(ROOT, "..");
const PROMPT_FILE = path.join(ROOT, "prompts.md");
const MARKER = "Generated by ALICE CODING. Source: knowledge/prompts.md.";

function fail(message, code = 1) {
  console.error(`ALICE wire failed: ${message}`);
  process.exit(code);
}

function readBakedPrompt() {
  if (!fs.existsSync(PROMPT_FILE)) {
    fail("prompts.md was not found. Complete INITIALIZATION Step 7 first.");
  }
  const prompt = fs.readFileSync(PROMPT_FILE, "utf8").trim();
  if (!prompt) fail("prompts.md is empty.");
  if (!prompt.includes("## NHIỆM VỤ")) {
    fail("prompts.md is not an ALICE vibe base prompt (missing '## NHIỆM VỤ').");
  }
  const placeholders = ["<PROJECT>", "<Bệ hạ chỉ cần điền việc cần làm ở đây>"];
  const unresolved = placeholders.find((value) => prompt.includes(value));
  if (unresolved) {
    fail(`prompts.md still contains the unresolved placeholder ${unresolved}.`);
  }
  return prompt;
}

function markdownAdapter(frontmatter, prompt, taskBlock) {
  return [
    "---",
    ...frontmatter,
    "---",
    "",
    `<!-- ${MARKER} -->`,
    "",
    "Nạp toàn bộ chỉ dẫn dưới đây làm chỉ dẫn đứng cho phiên làm việc hiện tại.",
    "Nếu có xung đột, system/developer instruction và luật project có ưu tiên cao hơn.",
    "",
    prompt,
    "",
    "## NHIỆM VỤ CỦA LƯỢT NÀY",
    taskBlock,
    "",
  ].join("\n");
}

function buildTargets(prompt) {
  const description = "Nạp base prompt ALICE đã bake và bắt đầu một task vibe coding theo đúng rules, memory, telemetry và verify của project.";
  const portable = markdownAdapter(
    [
      "name: alice",
      `description: ${description}`,
    ],
    prompt,
    "Nội dung người dùng viết cùng lời gọi skill `$alice` là nhiệm vụ cần thực hiện. Nếu chưa có nhiệm vụ, hỏi đúng một câu ngắn để lấy nhiệm vụ.",
  );
  const claude = markdownAdapter(
    [
      "name: alice",
      `description: ${description}`,
      "disable-model-invocation: true",
      "argument-hint: <task>",
    ],
    prompt,
    "$ARGUMENTS",
  );
  const opencode = markdownAdapter(
    [
      `description: ${description}`,
    ],
    prompt,
    "$ARGUMENTS",
  );
  const geminiPrompt = [
    `<!-- ${MARKER} -->`,
    "Nạp toàn bộ chỉ dẫn dưới đây làm chỉ dẫn đứng cho phiên làm việc hiện tại.",
    "Nếu có xung đột, system/developer instruction và luật project có ưu tiên cao hơn.",
    "",
    prompt,
    "",
    "## NHIỆM VỤ CỦA LƯỢT NÀY",
    "{{args}}",
  ].join("\n");
  const gemini = [
    `# ${MARKER}`,
    `description = ${JSON.stringify(description)}`,
    `prompt = ${JSON.stringify(geminiPrompt)}`,
    "",
  ].join("\n");

  return [
    [path.join(PROJECT_ROOT, ".agents", "skills", "alice", "SKILL.md"), portable, "Codex/OpenCode skill"],
    [path.join(PROJECT_ROOT, ".claude", "skills", "alice", "SKILL.md"), claude, "Claude Code skill"],
    [path.join(PROJECT_ROOT, ".opencode", "commands", "alice.md"), opencode, "OpenCode command"],
    [path.join(PROJECT_ROOT, ".gemini", "commands", "alice.toml"), gemini, "Gemini CLI command"],
  ];
}

function isAliceOwned(file) {
  return fs.existsSync(file) && fs.readFileSync(file, "utf8").includes(MARKER);
}

function writeAll(targets) {
  const conflicts = targets
    .filter(([file]) => fs.existsSync(file) && !isAliceOwned(file))
    .map(([file]) => path.relative(PROJECT_ROOT, file));
  if (conflicts.length) {
    fail(`refusing to overwrite non-ALICE adapter(s): ${conflicts.join(", ")}`, 2);
  }

  for (const [file, content, label] of targets) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, "utf8");
    console.log(`  WIRED  ${label}: ${path.relative(PROJECT_ROOT, file)}`);
  }
}

const prompt = readBakedPrompt();
writeAll(buildTargets(prompt));
console.log("\nALICE adapters are ready:");
console.log("  Claude Code / OpenCode / Gemini CLI: /alice <task>");
console.log("  Codex: $alice <task> (Codex does not expose repo skills as /alice)");
console.log("Commit the generated adapter files with the project so the team gets the same entry point.");
